### ISSUE TITLE
Troubleshooting Installation

### ISSUE THREAD

**Issue by Heiko-san** [bigstepinc/jmeter_s3_custom_sampler#3]
Hi,

I would like to use your plugin to do a permance test agains AWS s3.
Unfortunately I'm not that familiar with Java and Jmeter.
I successfully compiled the plugin and installed jmeter 2.11.
But I'm having the following issues:
- I don't know where I have to place the plugin so that jmeter recognizes it.
- I'm confused not having the "Sampler" section in my jmeter at all (there are Threads, Test Fragment, Config Element, Timer, Pre Processors, Post Processors,Assertions and Listener)

Any help would be appreciated.

**Comment by Heiko-san** [comment]
Update: We got the installation running.
But still we get no results.
We have a configuration with Thread Group 10 users a 100 requests.
A View Result in Table Listener and the Java Sampler.
What we want to test is Downloadspeed, so we configured:
- GET
- bucketname
- keys
- object is "testfile.png" which resides in thebucket at top level
- local_file_path is set to /tmp/ to ensure permissions won't fail
- I'm not sure if /how we have to set proxy_host/port , I'd say we don't need them but the are automatically added again if I save
  If I run the test It finishes very fast and there are no results in the table.
  If I replace the s3 check with a normal http check (to any other URL) everything works fine, so I think the problem must be the s3 check.
  How can one debug what is going wrong here?

**Comment by alexandrubordei** [comment]
Try increasing the debug level of jmeter from the log4j.properties file. There has to be some error somewhere usually tied to missing/missmatched aws client libs.

Sent from my iPhone

On 26 nov. 2015, at 17:01, Heiko-san notifications@github.com wrote:

Update: We got the installation running.
But still we get no results.
We have a configuration with Thread Group 10 users a 100 requests.
A View Result in Table Listener and the Java Sampler.
What we want to test is Downloadspeed, so we configured:

GET
bucketname
keys
object is "testfile.png" which resides in thebucket at top level
local_file_path is set to /tmp/ to ensure permissions won't fail
I'm not sure if /how we have to set proxy_host/port , I'd say we don't need them but the are automatically added again if I save If I run the test It finishes very fast and there are no results in the table. If I replace the s3 check with a normal http check (to any other URL) everything works fine, so I think the problem must be the s3 check. How can one debug what is going wrong here?

**Comment by Heiko-san** [comment]
Thanks, and sorry for the somehow stupid questions , but as I said , its our first time using both, java and jmeter.
There is indeed an exception:

2015/11/26 16:07:46 ERROR - jmeter.threads.JMeterThread: Test failed! java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.ClientConfiguration
    at com.bigstep.S3Sampler.runTest(S3Sampler.java:68)
    at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:191)
    at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:434)
    at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:261)
    at java.lang.Thread.run(Thread.java:745)

I've unzipped the aws-java-sdk-1.10.37.jar and the class ClientConfiguration seems to be there.
Maybe the SDK Version is "to new" ? 
I tried 1.8.1 now, but getting another error in the debug window:

015/11/26 16:28:44 ERROR - jmeter.threads.JMeterThread: Test failed! java.lang.NoClassDefFoundError: Could not initialize class com.amazonaws.internal.config.InternalConfig$Factory
    at com.amazonaws.ServiceNameFactory.getServiceName(ServiceNameFactory.java:34)
    at com.amazonaws.AmazonWebServiceClient.computeServiceName(AmazonWebServiceClient.java:707)
    at com.amazonaws.AmazonWebServiceClient.getServiceNameIntern(AmazonWebServiceClient.java:680)
    at com.amazonaws.AmazonWebServiceClient.computeSignerByURI(AmazonWebServiceClient.java:282)
    at com.amazonaws.AmazonWebServiceClient.setEndpoint(AmazonWebServiceClient.java:160)
    at com.amazonaws.services.s3.AmazonS3Client.setEndpoint(AmazonS3Client.java:491)
    at com.amazonaws.services.s3.AmazonS3Client.init(AmazonS3Client.java:463)
    at com.amazonaws.services.s3.AmazonS3Client.<init>(AmazonS3Client.java:359)
    at com.bigstep.S3Sampler.runTest(S3Sampler.java:75)
    at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:191)
    at org.apache.jmeter.threads.JMeterThread.process_sampler(JMeterThread.java:434)
    at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:261)
    at java.lang.Thread.run(Thread.java:745)

Last thing before that stack trace was:
2015/11/26 16:28:44 INFO  - com.amazonaws.http.AmazonHttpClient: Configuring Proxy. Proxy Host:  Proxy Port: 8080

so i think its an issue with the proxy configuration
what is this proxy good for, to what do I need to set the values?

Doesn't seem to be the proxy setting's fault. I installed squid and proxied to localhost:3128 but nothing changes.
I tried different jmeter versions (also 2.11 and 2.13) with both versions of the aws sdk (1.10.37 & 1.8.1) and also changed java 1.7 for 1.6, but nothing changes.
I can't seem to find any useful hints on this error using google.
So right now -> no idea how to get it running.

**Comment by alexandrubordei** [comment]
No worries.

The problem seems to be the fact that jmeter can’t find the aws sdk jars. Try adding all the jars in both ./lib/opt and ./lib. directories. 

Alex

**Comment by Heiko-san** [comment]
Hi,

before adding the SDK there was a very different error, clearly saying that the libs are missing.
During my tries above I had the SDK in lib/ext/ just besides the plugin itself.
I copied it now to lib/ and lib/opt/ in addition (had to create lib/opt/ first, since my jmeter installation didn't have it).
But I'm still getting the same error.

**Comment by alexandrubordei** [comment]
Maybe it's a different SDK version, I haven't maintained this in a while. Take a look at the class name, is it still present in the javadoc? Also try jar -tf on the jars from the sdk to look for the classes there. You might need either an older sdk or to change the code slightly. 

Sent from my iPhone

On 29 nov. 2015, at 14:22, Heiko-san notifications@github.com wrote:
D 
Hi,

before adding the SDK there was a very different error, clearly saying that the libs are missing.
During my tries above I had the SDK in lib/ext/ just besides the plugin itself.
I copied it now to lib/ and lib/opt/ in addition (had to create lib/opt/ first, since my jmeter installation didn't have it).
But I'm still getting the same error.
